-- Supabase 表和存储桶创建脚本
-- 在 Supabase SQL Editor 中执行此脚本

-- 如果表已存在，需要添加新列
-- ALTER TABLE records ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
-- ALTER TABLE records ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

-- 创建 records 表（如果是新表）
CREATE TABLE IF NOT EXISTS records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    location TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    tag TEXT,
    image_uri TEXT,
    timestamp TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 启用行级安全性 (RLS)
ALTER TABLE records ENABLE ROW LEVEL SECURITY;

-- 创建允许所有人读取的策略
CREATE POLICY "Allow public read access"
ON records FOR SELECT
USING (true);

-- 创建允许所有人插入的策略
CREATE POLICY "Allow public insert access"
ON records FOR INSERT
WITH CHECK (true);

-- 创建允许所有人更新的策略
CREATE POLICY "Allow public update access"
ON records FOR UPDATE
USING (true);

-- 创建允许所有人删除的策略
CREATE POLICY "Allow public delete access"
ON records FOR DELETE
USING (true);

-- 注意: 存储桶需要在 Supabase Dashboard 中手动创建
-- 步骤:
-- 1. 进入 Storage -> New bucket
-- 2. 名称: images
-- 3. Public bucket: 勾选
-- 4. Create bucket
-- 5. 进入 Settings -> RLS Policies
-- 6. 为 SELECT、INSERT、UPDATE、DELETE 创建允许所有人访问的策略

-- 创建评论表
CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    author TEXT DEFAULT '我',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 启用行级安全性 (RLS)
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;

-- 创建允许所有人读取的策略
CREATE POLICY "Allow public read comments"
ON comments FOR SELECT
USING (true);

-- 创建允许所有人插入的策略
CREATE POLICY "Allow public insert comments"
ON comments FOR INSERT
WITH CHECK (true);

-- 创建允许所有人删除的策略
CREATE POLICY "Allow public delete comments"
ON comments FOR DELETE
USING (true);
